In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [ ]:
data=pd.read_csv("https://raw.githubusercontent.com/huynhthanh98/ML/master/lab-03/heart.csv")
data

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0     63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1     37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2     41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3     56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4     57    0   0       120   354    0  ...      1      0.6      2   0     2       1
..   ...  ...  ..       ...   ...  ...  ...    ...      ...    ...  ..   ...     ...
298   57    0   0       140   241    0  ...      1      0.2      1   0     3       0
299   45    1   3       110   264    0  ...      0      1.2      1   0     3       0
300   68    1   0       144   193    1  ...      0      3.4      1   2     3       0
301   57    1   0       130   131    0  ...      1      1.2      1   1     3       0
302   57    0   1       130   236    0  ...      0      0.0      1   1     2       0

[303 rows x 14 columns]

In [ ]:
#Hàm sigmoid
def sigmoid(W,X):
  return 1/(1+np.exp((-np.matmul(X,W))))

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(data.iloc[:,:13].values,data.loc[:,"target"].values, test_size=0.33, random_state=42)

min=np.min(X_train,axis=0)
max=np.max(X_train,axis=0)
X_train=(X_train-min)/(max -min)
X_test=(X_test-min)/(max-min)

In [ ]:
#Thêm 1 cột những số 1 vào X_train
X_train_bar=np.concatenate([np.ones([X_train.shape[0],1]),X_train],axis=1)
y_train = y_train.reshape(-1,1)
X_train_bar.shape

(203, 14)

In [ ]:
# learning rate
lr=0.01

# Tạo W (Initial)
W_init=np.zeros([X_train_bar.shape[1],1])
W = W_init
for epoch in range(50000):
  prediction=sigmoid(W,X_train_bar) # Dự đoán

  error=-np.mean((y_train*np.log(prediction)+(1-y_train)*np.log(1-prediction)),axis=0) #Tính error

  gradient=np.mean((prediction-y_train).T.dot(X_train_bar),axis=0) #Tính Gradient
  
  gradient=gradient.reshape(-1,1)
  
  W=W-lr*gradient #cập nhật W

  #if epoch % 10000==0:
  #  print('error in {} = {}'.format(epoch,error))
print(W)

[[ 2.239255  ]
 [ 0.98966787]
 [-1.45083978]
 [ 3.01045104]
 [-0.96117111]
 [-0.81113204]
 [ 0.31742796]
 [ 1.31865356]
 [ 1.89440786]
 [-1.17156853]
 [-2.56094147]
 [ 2.11477148]
 [-5.00610673]
 [-4.30201073]]


In [ ]:
#test
X_test_bar=np.concatenate([np.ones([X_test.shape[0],1]),X_test],axis=1)
a=sigmoid(W,X_test_bar)
np.mean(np.where(a>0.5,1,0)==y_test.reshape(-1,1))

0.81

In [ ]:
#Kiểm tra lại
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=0).fit(X_train, y_train)
clf.score(X_test,y_test)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.81

**Câu 2 :**


In [ ]:
from sklearn import datasets

# import some data to play with
iris = datasets.load_iris()
X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(
  X, y, test_size=0.33, random_state=42)


max=np.max(X_train,axis=0)
min=np.min(X_train,axis=0)

X_train=(X_train-min)/(max-min)
X_test=(X_test-min)/(max-min)


y_train_onehot = np.zeros( (y_train.size, y_train.max() + 1),dtype=int)
y_train_onehot[np.arange(y_train.size), y_train.reshape(-1)] = 1

y_test_onehot = np.zeros( (y_test.size, y_test.max() + 1) ,dtype=int)
y_test_onehot[np.arange(y_test.size), y_test.reshape(-1)] = 1


X_train_bar=np.concatenate([np.ones([X_train.shape[0],1]),X_train],axis=1)
X_test_bar=np.concatenate([np.ones([X_test.shape[0],1]),X_test],axis=1)
y_train = y_train.reshape(-1,1)
X_test_bar.shape


(50, 5)

In [ ]:
#Normalizaition
min=np.min(X_train,axis=0)
max=np.max(X_train,axis=0)
X_train=(X_train-min)/(max-min)
X_test=(X_test-min)/(max-min)

In [ ]:
# learning rate
lr = 0.01
W_init = np.zeros([X_train_bar.shape[1],1])
W = W_init
for epoch in range(10000):
  expi=np.exp(np.matmul(X_train_bar,W)) 
  expsum=np.sum(expi,axis=1)   
  soft1=expi/expsum.reshape(-1,1)  
  a=(-y_train_onehot+soft1)    
  W_temp=np.zeros([X_train_bar.shape[1],y_train_onehot.shape[1]])
  #W_temp
  for i in range(y_train_onehot.shape[1]):
    temp=i+1
    W_temp[:,i:temp]=np.mean(a[:,i:temp]*X_train_bar,axis=0).reshape(-1,1)
#cal error
  W=W-lr*W_temp

  for i in range(y_train_onehot.shape[1]):
    error=np.exp(np.matmul(X_train_bar,W))/np.sum(np.exp(np.matmul(X_train_bar,W)),axis=1).reshape(-1,1)
    error=-y_train_onehot*np.log(error)
    error=np.sum(np.mean(error,axis=0))

  #if epoch % 10000==0:
  #  print(list_error[-1])
print(W)

[[ 1.52359793  1.06914237 -2.6127403 ]
 [-1.34719735  0.16678187  1.17150371]
 [ 2.34277218 -1.69359226 -0.65837083]
 [-2.93842708  0.79217688  2.13655019]
 [-2.76035492 -0.12435922  2.87538913]]


In [ ]:
expi=np.exp(np.matmul(X_test_bar,W))
expsum=np.sum(expi,axis=1)   
#Kết quả
np.mean(y_test.reshape(-1)==np.argmax(expi/expsum.reshape(-1,1),axis=1))

0.9

In [ ]:
#dùng sklearn
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=0).fit(X_train, y_train)
clf.score(X_test,y_test)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.9