In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
data=pd.read_csv('https://raw.githubusercontent.com/huynhthanh98/ML/master/lab-04/train.csv')
data.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [3]:
data=data.drop(["Cabin","Age","PassengerId","Name","Ticket"],axis=1)
data=data.dropna()

In [4]:
print(data)

     Survived  Pclass     Sex  SibSp  Parch     Fare Embarked
0           0       3    male      1      0   7.2500        S
1           1       1  female      1      0  71.2833        C
2           1       3  female      0      0   7.9250        S
3           1       1  female      1      0  53.1000        S
4           0       3    male      0      0   8.0500        S
..        ...     ...     ...    ...    ...      ...      ...
886         0       2    male      0      0  13.0000        S
887         1       1  female      0      0  30.0000        S
888         0       3  female      1      2  23.4500        S
889         1       1    male      0      0  30.0000        C
890         0       3    male      0      0   7.7500        Q

[889 rows x 7 columns]


In [5]:
data_train, data_test = train_test_split( data, test_size=0.2, random_state=42)

In [6]:
def get_features(data=data_train):
  Survived=data["Survived"].values
  Pclass=data["Pclass"].values
  Sex=data["Sex"].values
  SibSp=data["SibSp"].values
  Parch=data["Parch"].values
  Embarked=data["Embarked"].values
  Fare=data["Fare"].values
  return Survived, Pclass, Sex, SibSp, Parch, Embarked,Fare

Survived_train, Pclass_train, Sex_train, SibSp_train, Parch_train,Embarked_train,Fare_train=get_features()
Survived_test, Pclass_test, Sex_test, SibSp_test, Parch_test,Embarked_test,Fare_test=get_features(data=data_test)

In [7]:
#Phân tích thử các giá trị có trong mỗi feature
for i in data_train:
  print(i)
  print(data_train[i].unique())

Survived
[1 0]
Pclass
[1 3 2]
Sex
['female' 'male']
SibSp
[0 1 8 5 4 2 3]
Parch
[0 2 1 3 6 4 5]
Fare
[151.55    14.4542   7.925   69.55    46.9     31.275    7.8958  35.5
   0.      26.      23.25    15.5      7.7875  13.5      6.4958  26.55
   7.5208   7.2292  53.1     25.4667  31.3875   8.6625  34.0208   7.125
  52.       7.8875  14.4583  83.1583   8.05    90.       7.725   39.6
  21.075    7.7333   7.25    77.2875   9.5     12.65    10.5     55.
   7.6292   7.75     7.8542  24.15    57.9792  15.      39.6875   7.225
 227.525   17.8      9.5875 113.275    7.8292  13.      30.5      9.
  71.       4.0125   7.05    78.85     8.85    27.75    27.7208 153.4625
   8.3     19.2583  14.5    133.65    76.7292  26.2833  20.525    7.8792
  29.7     15.7417  30.6958  51.8625  81.8583  56.4958  39.       7.4958
   7.7958   7.55    12.      93.5     21.      12.35    16.1     78.2667
  35.      55.9      7.8     30.      18.      26.2875  83.475   59.4
  77.9583  28.7125  56.9292   7.65    22.358

**Câu 1 :**


In [8]:
# Xác suất tiên nghiệm 
P_Survived = np.sum((Survived_train == 1))/len(Survived_train)
P_notSurvived = np.sum((Survived_train == 0))/len(Survived_train)
print(data_test)

     Survived  Pclass     Sex  SibSp  Parch      Fare Embarked
281         0       3    male      0      0    7.8542        S
435         1       1  female      1      2  120.0000        S
39          1       3  female      1      0   11.2417        C
418         0       2    male      0      0   13.0000        S
585         1       1  female      0      2   79.6500        S
..        ...     ...     ...    ...    ...       ...      ...
433         0       3    male      0      0    7.1250        S
807         0       3  female      0      0    7.7750        S
25          1       3  female      1      5   31.3875        S
85          1       3  female      3      0   15.8500        S
10          1       3  female      1      1   16.7000        S

[178 rows x 7 columns]


In [9]:
features = ["Sex","Pclass","Embarked"]

P_Survived_combine = np.ones(data_test.shape[0])
P_notSurvived_combine = np.ones(data_test.shape[0])
for i in features:
  col_train = data_train[i]
  col_test = data_test[i]

  P_1 = []
  P_0 = []
  for j in col_train.unique():
    
    P1 = np.sum((col_train[Survived_train ==1]==j))/np.sum((Survived_train == 1))
    P_1.append(P1)
    P0 = np.sum((col_train[Survived_train ==0]==j))/np.sum((Survived_train == 0))
    P_0.append(P0)

  P_col_Survived = np.zeros(col_test.shape)
  P_col_notSurvived = np.zeros(col_test.shape)

  ##Tính xác xuất hậu nghiệm trên tập trên tập test)
  
  for k in range(len(col_test.unique())): 
    P_col_Survived += P_1[k]*(col_test==col_train.unique()[k]).astype(float) 
    P_col_notSurvived += P_0[k]*(col_test==col_train.unique()[k]).astype(float)
  
  ## Tính P(x1,...,xn | Survived) = P(x1|Survived) *...*P(xn | Survived)
  P_Survived_combine *= P_col_Survived
  P_notSurvived_combine *= P_col_notSurvived
  
## Tính P(x1,...,xn | Survived) * P(Survived)
P_Survived_combine =P_Survived_combine * P_Survived
P_notSurvived_combine *= P_notSurvived

## Kết quả
np.mean((P_Survived_combine>P_notSurvived_combine).astype(float)==Survived_test)


0.7808988764044944

In [10]:
## Dùng sklearn
data_train1=data_train[["Sex","Pclass","Embarked"]]
data_test1=data_test[["Sex","Pclass","Embarked"]]

In [11]:
from sklearn.naive_bayes import CategoricalNB
from sklearn import preprocessing

le = preprocessing.LabelEncoder()
for i in features:
  data_train1[i] = le.fit_transform(data_train1[i])
  data_test1[i] = le.fit_transform(data_test1[i])

print(data_test1)

     Sex  Pclass  Embarked
281    1       2         2
435    0       0         2
39     0       2         0
418    1       1         2
585    0       0         2
..   ...     ...       ...
433    1       2         2
807    0       2         2
25     0       2         2
85     0       2         2
10     0       2         2

[178 rows x 3 columns]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys


In [12]:
nb = CategoricalNB(alpha=1.0e-10).fit(data_train1, Survived_train)
print(nb.score(data_test1,Survived_test))

0.7808988764044944


**Câu 2 :**

In [13]:
def normal(x, mean, std):
    return 1/(np.sqrt(2*np.pi)*std)*np.exp(-np.square(x-mean)/(2*np.square(std)))

In [14]:
features = ["SibSp","Parch","Fare"]
P_col_Survived = 1
P_col_notSurvived = 1
for i in features:
  col_train = data_train[i]
  col_test = data_test[i]

  ## Tính Tham Số

  col_mean_Survived = np.mean(col_train[Survived_train == 1])
  col_std_Survived = np.std(col_train[Survived_train == 1])

  col_mean_notSurvived = np.mean(col_train[Survived_train == 0])
  col_std_notSurvived = np.std(col_train[Survived_train == 0])

  P_col_Survived *= normal(col_test,col_mean_Survived,col_std_Survived)
  P_col_notSurvived *= normal(col_test,col_mean_notSurvived,col_std_notSurvived)

P_Survived_combine=P_Survived*P_col_Survived
P_notSurvived_combine= P_notSurvived*P_col_notSurvived

print(np.mean((P_Survived_combine>P_notSurvived_combine).astype(int)==Survived_test))

0.6910112359550562


In [15]:
## Dùng sklearn
data_train2=data_train[["SibSp","Parch","Fare"]]
data_test2=data_test[["SibSp","Parch","Fare"]]

In [16]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB().fit(data_train2, Survived_train)
print(nb)
print(np.mean(Survived_test == nb.predict(data_test2)))

GaussianNB(priors=None, var_smoothing=1e-09)
0.6910112359550562


**Câu 3 :**

In [17]:
df = pd.read_csv("https://raw.githubusercontent.com/dinhvietcuong1996/Lab-MachineLearningCourse/master/Lab04/lienminh.csv")
df.head()

killsDiff  minionsKilledDiff  wardPlacedDiff  ... heralds dragons teamWins
0          3                 -2              13  ...    none    none      red
1          0                -66               0  ...     red     red      red
2         -4                -17               0  ...    none    blue      red
3         -1                -34              28  ...    blue    none      red
4          0                -15              58  ...    none     red      red

[5 rows x 7 columns]

In [18]:
killsDiff = df['killsDiff'].values
minionsKilledDiff = df['minionsKilledDiff'].values
wardPlacedDiff = df['wardPlacedDiff'].values
firstBlood = df['firstBlood'].values
heralds = df['heralds'].values
dragons = df['dragons'].values

teamWins = df['teamWins'].values

## P(teamWins)

P_blueWins=0.5
P_redWins=0.5


In [19]:
#Phân tích thử các giá trị có trong mỗi feature
for i in df:
  print(i)
  print(df[i].unique())

killsDiff
[  3   0  -4  -1   2   1  -8   6  -5   8   5  -9  -2  -3  -6  -7   4   9
   7 -11  11 -13  10 -10  12  13 -12  16 -15  14 -14 -17  15]
minionsKilledDiff
[  -2  -66  -17  -34  -15    4   61   52  -51  -27   15  -31  -19  -18
  -28   53  -11   -6    7   18   11  -24   26    8    1   12   -3  -21
   17  -23    9   46   10  -60   55  -38  -35    3   31    5   38   19
   23  -37  -25   54   -4  -52   -1  -43   14   24   37   -5   32   16
   44   21   28   41  -47  -22  112  -46   64   39  -13   27   13   20
   -8  -70  -16  -42  -10  -36  -12   85  -26   36   -7  -50   35  -54
   29  -41   74  -14  -20  -32  -63  -49    6  -71   33  -29    2   47
   40   34  -53  -68  -45   50   63   22   43  -40   25 -101    0  -75
  -39  104   96  -62   56   30   62   82   45  -61   59   69   42  -58
  -93   76   65   57   49  -30  -44   51   79  -59   -9  110  -72   48
  -76   72  -64  -33 -120   60  -84   77  -73  -48  -83  -98  -92   84
   71  -81  -57  -74   80  -82   73  -65  100   89   83 

In [20]:
## Tính P(Categorical)
features = ["firstBlood","heralds","dragons"]

P_blueWins_combine1 = np.ones(df.shape[0])
P_redWins_combine1 = np.ones(df.shape[0])
for i in features:
  col_train = df[i]
  col_test = df[i]

  P_1 = []
  P_0 = []
  for j in col_train.unique():
    
    P1 = np.sum((col_train[teamWins =='blue']==j))/np.sum((teamWins == 'blue'))
    P_1.append(P1)
    P0 = np.sum((col_train[teamWins == 'red']==j))/np.sum((teamWins == 'red'))
    P_0.append(P0)

  ##Tính xác xuất hậu nghiệm trên tập trên tập test

  P_col_blueWins = np.zeros(col_test.shape)
  P_col_redWins = np.zeros(col_test.shape)
  for k in range(len(col_test.unique())): 
    P_col_blueWins += P_1[k]*(col_test==col_train.unique()[k]).astype(float) 
    P_col_redWins += P_0[k]*(col_test==col_train.unique()[k]).astype(float)
  
  ## Tính P(x1,...,xn | teamWins) = P(x1|teamWins) *...*P(xn | teamWins)
  P_blueWins_combine1 *= P_col_blueWins
  P_redWins_combine1 *= P_col_redWins

In [21]:
## Tính P(Gaussian)
features = ['killsDiff','minionsKilledDiff','wardPlacedDiff']

P_col_blueWins = 1
P_col_redWins = 1
for i in features:
  col_train = df[i]
  col_test = df[i]

  ## Tính Tham Số

  col_mean_blueWins = np.mean(col_train[teamWins == 'blue'])
  col_std_blueWins = np.std(col_train[teamWins == 'blue'])

  col_mean_redWins = np.mean(col_train[teamWins == 'red'])
  col_std_redWins = np.std(col_train[teamWins == 'red'])

  ## Tính P(x1,...,xn | teamWins) = P(x1|teamWins) *...*P(xn | teamWins)
  
  P_col_blueWins *= normal(col_test,col_mean_blueWins,col_std_blueWins)
  P_col_redWins *= normal(col_test,col_mean_redWins,col_std_redWins)


In [22]:
## Tính P = P(teamWins)*P(Categorical)*P(Gaussian)

P_blueWins_combine=P_blueWins*P_col_blueWins*P_blueWins_combine1
P_redWins_combine=P_redWins*P_col_redWins*P_redWins_combine1

In [23]:
# Team Blue Wins

print(np.mean((P_blueWins_combine>P_redWins_combine).astype(float)==(teamWins == 'blue').astype(float)))

0.7116104868913857


In [24]:
# Team Red Wins

print(np.mean((P_redWins_combine>P_blueWins_combine).astype(float)==(teamWins == 'blue').astype(float)))

0.2883895131086142
